- name: Set up Raspberry Pi
  hosts: raspberry_pi
  become: yes
  tasks:
    - name: Install requirements
      local_action: command ansible-galaxy install -r requirements.yml
      become: no
      tags:
        - setup
    - name: Setup
      include_role:
        name: reitermarkus.raspberry_pi.setup
      vars:
        timezone: Europe/Vienna
        serial: on
        serial_console: off
        watchdog: on
    - name: Build program
      local_action: command cargo install --bin smart-meter-server --path . --root target
      become: no
    - name: Install program
      copy:
        src: target/bin/smart-meter-server
        dest: /usr/local/bin/smart-meter-server
        mode: 0755
    - name: Enable systemd-networkd-wait-online service
      systemd:
        name: systemd-networkd-wait-online
        enabled: yes
    - name: Load key
      community.sops.load_vars:
        file: key.sops.yaml
        name: key
    - name: Install service
      copy:
        content: |
          [Unit]
          Description=smart-meter-server
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=simple
          Environment=RUST_LOG=info
          Environment=PORT=8889
          Environment=SERIAL_PORT=/dev/serial0
          Environment=KEY={{ key.key }}
          ExecStart=/usr/local/bin/smart-meter-server
          Restart=always
          RestartSec=1

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/smart-meter-server.service
    - name: Enable service
      systemd:
        name: smart-meter-server
        enabled: yes
        state: restarted
